"""add_allowed_domains_to_firms

Revision ID: 968d26aaac9c
Revises: c249c56b7b7c
Create Date: 2026-07-13 00:52:25.946434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '968d26aaac9c'
down_revision: Union[str, Sequence[str], None] = 'c249c56b7b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firms', sa.Column('allowed_domains', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firms', 'allowed_domains')
    # ### end Alembic commands ###
