"""add_multi_tenancy_and_approval

Revision ID: b9f07d65b257
Revises: fb332ebe2708
Create Date: 2026-07-12 22:33:07.593110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9f07d65b257'
down_revision: Union[str, Sequence[str], None] = 'fb332ebe2708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ── Step 1: Create new tables ──
    op.create_table('firms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_firms_id'), 'firms', ['id'], unique=False)
    
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    
    op.create_table('firm_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('technical_role', postgresql.ENUM('admin', 'moderator', 'viewer', name='technicalrole', create_type=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'firm_id', name='uq_firm_user')
    )
    op.create_index(op.f('ix_firm_users_id'), 'firm_users', ['id'], unique=False)
    
    op.create_table('approval_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.Enum('assignment', 'engagement', 'client', 'team_member', 'leave', name='resourcetype'), nullable=False),
    sa.Column('operation', sa.Enum('create', 'update', 'delete', name='operationtype'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('approver_role', postgresql.ENUM('admin', 'moderator', 'viewer', name='technicalrole', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'resource_type', 'operation', name='uq_approval_rule')
    )
    op.create_index(op.f('ix_approval_rules_id'), 'approval_rules', ['id'], unique=False)
    
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.Enum('assignment', 'engagement', 'client', 'team_member', 'leave', name='resourcetype'), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.Enum('create', 'update', 'delete', name='operationtype'), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approvalstatus'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_id'), 'approval_requests', ['id'], unique=False)
    
    # ── Step 2: Seed default firm ──
    conn = op.get_bind()
    conn.execute(sa.text(
        "INSERT INTO firms (name, code, is_active) VALUES ('PKF Sridhar & Santhanam', 'PKF', true)"
    ))
    default_firm_id = conn.execute(sa.text("SELECT id FROM firms WHERE code = 'PKF'")).scalar()
    
    # ── Step 3: Add firm_id columns as NULLABLE first ──
    op.add_column('clients', sa.Column('firm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'firms', ['firm_id'], ['id'], ondelete='RESTRICT')
    
    op.add_column('system_settings', sa.Column('firm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'system_settings', 'firms', ['firm_id'], ['id'], ondelete='SET NULL')
    
    op.add_column('team_members', sa.Column('firm_id', sa.Integer(), nullable=True))
    op.add_column('team_members', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'team_members', 'firms', ['firm_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'team_members', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    
    # ── Step 4: Migrate existing data to default firm ──
    conn.execute(sa.text(f"UPDATE clients SET firm_id = {default_firm_id} WHERE firm_id IS NULL"))
    conn.execute(sa.text(f"UPDATE team_members SET firm_id = {default_firm_id} WHERE firm_id IS NULL"))
    
    # Migrate existing users to firm_users (before dropping technical_role from users)
    conn.execute(sa.text(
        f"INSERT INTO firm_users (user_id, firm_id, technical_role, is_active) "
        f"SELECT id, {default_firm_id}, technical_role, is_active FROM users"
    ))
    
    # ── Step 5: Make firm_id NOT NULL now that data is migrated ──
    op.alter_column('clients', 'firm_id', nullable=False)
    op.alter_column('team_members', 'firm_id', nullable=False)
    
    # ── Step 6: Drop old technical_role columns ──
    op.drop_column('team_members', 'technical_role')
    op.drop_column('users', 'technical_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('technical_role', postgresql.ENUM('admin', 'moderator', 'viewer', name='technicalrole'), autoincrement=False, nullable=False))
    op.add_column('team_members', sa.Column('technical_role', postgresql.ENUM('admin', 'moderator', 'viewer', name='technicalrole'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_column('team_members', 'branch_id')
    op.drop_column('team_members', 'firm_id')
    op.drop_constraint(None, 'system_settings', type_='foreignkey')
    op.drop_column('system_settings', 'firm_id')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'firm_id')
    op.drop_index(op.f('ix_firm_users_id'), table_name='firm_users')
    op.drop_table('firm_users')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_approval_rules_id'), table_name='approval_rules')
    op.drop_table('approval_rules')
    op.drop_index(op.f('ix_approval_requests_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_firms_id'), table_name='firms')
    op.drop_table('firms')
    # ### end Alembic commands ###
